#!/usr/bin/env python
"""list images in .svg files"""

import os, re, sys

re_link1 = re.compile(
    r'xlink:href="(?P<uri_prefix>file:///)(?P<fname>.+)"')
re_link2 = re.compile(
    r'xlink:href="(?P<slash>/)(?P<fname>.+)"')
re_link3 = re.compile(
    r'xlink:href="(?P<fname>.+)"')

class Replacer:
    def __init__(self, source_fname):
        self.source_dir = os.path.split(os.path.abspath(source_fname))[0]
    def abs_repl(self,matchobj):
        abs_fname = '/' + matchobj.group('fname')
        print abs_fname
        return ''
    def rel_repl(self,matchobj):
        rel_fname = matchobj.group('fname')
        if not rel_fname.startswith('#'): # hack to non-filenames
            if not rel_fname.startswith('data:'): # hack to avoid printing embedded images
                print rel_fname
        return ''

def list_images_in_file(input_fname):
    replacer = Replacer( input_fname )

    for orig_line in open(input_fname).readlines():
        new_line1 = re_link1.sub( replacer.abs_repl, orig_line)
        new_line2 = re_link2.sub( replacer.abs_repl, new_line1)
        new_line3 = re_link3.sub( replacer.rel_repl, new_line2)

if __name__=='__main__':
    fnames = sys.argv[1:]
    for fname in fnames:
        list_images_in_file(fname)
